config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :applications, only: [:index]
  resources "studentapplications"
  resources "clients", only: [:new, :create]
  resources "sponsors", only: [:new, :create]
  resources "users"
  get '/about' => 'static_pages#about'
  get '/team' => 'static_pages#team'
  get '/home' => 'static_pages#home'
  get '/admin' => 'admin#index'
  get '/admin/viewapps' => 'admin#viewapps'
  get '/admin/editusers' => 'admin#editusers'
  get '/admin/viewessays/:id' => 'admin#viewessays'
  get '/admin/newdeadline' => 'admin#new_deadline'
  get '/admin/prompts' => 'admin#prompts'
  post '/studentapplications/change_status' => 'studentapplications#change_status'
  post '/users/update_or_destroy' => 'users#update_or_destroy'
  post '/admin/setdeadline' => 'admin#set_deadline'
  post '/admin/newprompt' => 'admin#newprompt'
  post '/admin/deleteprompt/:id' => 'admin#deleteprompt'
  

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/deadline.rb
class Deadline < ActiveRecord::Base
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/studentapplication.rb
class Studentapplication < ActiveRecord::Base
    belongs_to :user
    validates :major, presence: true
    validates :graduation, presence: true
    validates :info, presence: true
    mount_uploader :resume, AvatarUploader
    serialize :essay
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :studentapplication
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  # validates :email, :presence => true, :email => true

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :ensure_admin!
	
	def index
	end
	
	def viewapps
	end
	
	def viewessays
		app = Studentapplication.find(params[:id])
		@essay = app.essay
		@name = app.user.name
	end
	
	def new_deadline
		@date = Deadline.last
	end
	
	def set_deadline
		if not Deadline.last.nil?
			Deadline.last.destroy
		end
		deadline = Deadline.new(date_params)
		if deadline.date.nil?
			flash[:notice] = "Please select the date and time."
			redirect_to admin_newdeadline_path
			return
		end
		deadline.save!
		flash[:notice] = "Deadline #{deadline.date.strftime("%m/%d/%Y-%I:%M%p")} was successfully set."
		redirect_to admin_path
	end
	
	def prompts
	end
	
	def newprompt
		Prompt.create(:text => params["text"])
		redirect_to admin_prompts_path
	end
	
	def deleteprompt
		prompt = Prompt.find(params[:id])
		prompt.delete
		redirect_to admin_prompts_path
	end
	
	private
		def ensure_admin!
			unless user_signed_in? && current_user.member_type == 'admin'
				sign_out current_user
				redirect_to root_path
			end
		end
		
		def date_params
    	params.require(:date).permit(:date)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    home_path
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def client_params
    params.require(:client).permit(:name, :email, :info)
  end
  
  def new
    @client = Client.new
  end
  

  def create
    @client = Client.new(client_params)
    @client.save
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  
  def sponsor_params
    params.require(:sponsor).permit(:name, :email, :info)
  end
  
  def new
    @sponsor = Sponsor.new
  end
  

  def create
    @sponsor = Sponsor.new(sponsor_params)
    @sponsor.save
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_loggedin!
  
  def show
    @user = User.find(params[:id])
  end
  
  def update_or_destroy
    # Currently if you check yourself and click
    # delete, you'll delete yourself and be
    # redirected to the home page.
    
    # delete users
    if params.has_key?("delete")
      if params.has_key?("select_user")
        params["select_user"].each do |id|
          delete_user = User.find(id)
          delete_app = Studentapplication.find_by("user_id":id)
          unless delete_app.nil?
            delete_app.destroy
          end
          delete_user.destroy
        end
      end
    end
    
    # give admin
    if params.has_key?("giveadmin")
      admin = "admin"
      if params.has_key?("select_user")
        params["select_user"].each do |id|
          upgrade_user = User.find(id)
          upgrade_user.member_type = admin
          upgrade_user.save
        end
      end
    end
    
    # remove admin
    if params.has_key?("removeadmin")
      mem = ""
      if params.has_key?("select_user")
        params["select_user"].each do |id|
          dg_user = User.find(id)
          dg_user.member_type = mem
          dg_user.save
        end
      end
    end
    
    redirect_to admin_editusers_path
    
  end
  
  private
		def ensure_loggedin!
			unless user_signed_in?
				redirect_to new_user_session_path
			end
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Helper to determine whether
    # current path is active.
    # Look at application.html.haml for example usage.
    def active(path)
      "active" if current_page?(path)
    end

    def active_class?(*paths)
      active = false
      paths.each { |path| active ||= current_page?(path) }
      active ? 'active' : nil
    end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/studentapplications_helper.rb
module StudentapplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/editusers.html.haml
%body
  .container_graybox
    %p Edit Users
  =form_tag users_update_or_destroy_path, method: "post" do
    %table#users{:align => "center"}
      %thead
        %tr
          %th.center Name
          %th.center Email
          %th.center Member Type
          %th.center Sign in Count
          %th.center Last Sign in At
          %th.center=check_box_tag "Check All"
      %tbody
        - User.all.each do |user|
          %tr
            %td.name=user.name 
            %td.email=user.email
            %td.member_type=user.member_type
            %td.count=user.sign_in_count
            %td.last=user.last_sign_in_at
            
            %td.select=check_box_tag "select_user[]", user.id
    %br
    = button_tag 'Delete Users', name: "delete"
    = button_tag 'Give Admin', name: "giveadmin"
    = button_tag 'Remove Admin', name: "removeadmin"

app/views/admin/index.html.haml
%body
  .container_graybox
    %p Admin Panel
  %h2
    %a
    = link_to "Applications", admin_viewapps_path
  %h2
    %a
    = link_to "Edit Users", admin_editusers_path
  %h2
    %a
    = link_to "Set Application Deadline", admin_newdeadline_path
  %h2
    %a
    = link_to "Edit Essay Prompts", admin_prompts_path
  
    

app/views/admin/new_deadline.html.haml
.container
  %form
  %center
    %h1 Set Deadline
    %p
    %p
    %p
    %p
    = form_tag(admin_setdeadline_path, :method => :post) do
      %br
      %br
      = label_tag :date, "Date"
      = datetime_local_field :date, "date"
      %br (eg. DD/MM/YYYY, 11:59 PM)
      %br
      %br
      .form-actions
        = submit_tag 'Edit'
      %br
      %br
      %br
      %br

app/views/admin/prompts.html.haml
.container_graybox
  %p Essay Prompts
  
%br  
- Prompt.all.each do |essay|
  %div
    =content_tag :span, essay.text, :style => "font-weight:bold"
    =button_to "Delete Prompt", "/admin/deleteprompt/#{essay.id}"
  %br
  
=form_tag admin_newprompt_path, method: "post" do  
  %input{:type=>"text", :name => "text", :required => true}
  =button_tag "Add Essay Prompt"

app/views/admin/viewapps.html.haml
.container_graybox
  %p Applications
=form_tag studentapplications_change_status_path, method: "post" do
  %table#applications{:align => 'center'}
    %thead
      %tr
        %th{:style => 'text-align: center'} Name
        %th{:style => 'text-align: center'} Email
        %th{:style => 'text-align: center'} Major
        %th{:style => 'text-align: center'} Graduation Year
        %th{:style => 'text-align: center'} Info
        %th{:style => 'text-align: center'} Resume
        %th{:style => 'text-align: center'} Essay
        %th{:style => 'text-align: center'} Status
        %th{:style => 'text-align: center'}=check_box_tag 'Check All'
    %tbody
      - Studentapplication.all.each do |studentapplication|
        %tr
          %td.name=studentapplication.user.name 
          %td.email=studentapplication.user.email
          %td.major=studentapplication.major
          %td.grad=studentapplication.graduation
          %td.info=studentapplication.info
          %td.resume
            %a{:href => studentapplication.resume, :target => "_blank"}>#{studentapplication.resume_identifier}
          %td.essay=link_to "View Essays", "/admin/viewessays/#{studentapplication.id}", target: "_blank"
          %td.status=studentapplication.status
          %td.select=check_box_tag "select_user[]", studentapplication.id
  %br
  = text_area_tag 'text', '', size: "30x5", placeholder: "This message will be sent to those who have their application status changed"
  %br
  = button_tag 'Accept Selected', name: "accept"
  = button_tag 'Reject Selected', name: "reject"
// .container_graybox
//   %p Clients
// %table#clients{:align => 'center'}
//   %thead
//     %tr
//       %th Name
//       %th Email
//       %th Comments
//   %tbody
//     - Client.all.each do |client|
//       %tr
//         %td= client.name 
//         %td= client.email
//         %td= client.info
// %br
// .container_graybox
//   %p Sponsors
// %table#sponsors{:align => "center"}
//   %thead
//     %tr
//       %th Name
//       %th Email
//       %th Comments
//   %tbody
//     - Sponsor.all.each do |sponsor|
//       %tr
//         %td= sponsor.name 
//         %td= sponsor.email
//         %td= sponsor.info
// %br

app/views/admin/viewessays.html.haml
%h1="#{@name} Essays"
- Prompt.all.each_with_index do |prompt, index|
    %br
    %strong=prompt.text
    %br=@essay[index]
%br
%br
%br
// = button_to "Back to Applications", admin_viewapps_path, :method => "get"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css", :rel => "stylesheet"}/
    %title 180 DC at Berkeley
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        // Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/home"}
            =image_tag asset_path("logo.png"), :alt => "180 DC"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
          %ul.nav.navbar-nav.navbar-right
            %li.home
              %a{:href => "/home", :id => "home"} Home
            %li.about
              %a{:href => "/about", :id => "about"} About
            %li.teams
              %a{:href => "/team", :id => "teams"} Teams
            %li.applications
              %a{:href => "/applications", :id => "apps"} Apps
            - if user_signed_in? && current_user.member_type == 'admin'
              %li.admin
                = link_to "Admin", admin_path, class: active(admin_path), :id => "admin"
            - if user_signed_in?
              %li.logout
                = link_to 'Logout', destroy_user_session_path, :method => 'delete', :id => "logout"
              .container_loggedin
                %p 
                = 'signed in as ' + current_user.email
            - else
              %li.login  
                = link_to 'Login', new_user_session_path, :id => "login"
    %br
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    -elsif flash[:alert] 
      #warning.message= flash[:alert]
    %br
    = yield
    %footer
      .container
        .row
          .col-lg-12
            %p 180 DC - Berkeley

app/views/students/new.html.haml
.container
  %form
  %center
    %h1 Spring 2016 Application
    Info Session #1 - Monday Feb. 1st
    %br
    Barrows 170
    %br
      7pm - 9pm
      %p
        Info Session #2 - Tuesday Feb. 2nd
        %br
          Barrows 126
          %br 7pm - 9pm
      %p
        Case Workshop - Thursday Feb. 4th
        %br
          Barrows 20
          %br 7pm - 9pm
      %p
        ***Application Deadline****
        %br Friday Feb 5th - 11:59pm
      %p Interviews - Sunday Feb 7th - Wednesday Feb 10th
      %p
        Consultant Welcome Night (if selected) - Thursday Feb. 11
        %br 7pm
      %p
        Email
        %a{:href => "mailto:recruitment.ucb@180dc.org"} recruitment.ucb@180dc.org
        regarding questions.
    %p
    %p
    %p
    %p
    %p
    = form_tag('/students#create', :method => :post) do
      %h2 Candidate Info
      %br
      %h3 Your Name
      = label :student, :name
      = text_field :student, 'name', required: true
      %br
      %h3 Your Email
      = label :student, :email
      = text_field :student, 'email', required: true
      %br
      %h3 What is your Major?
      = label :student, :major
      = text_field :student, 'major', required: true
      %br
      %h3 When do you graduate?
      = label :student, :graduation
      = text_field :student, 'graduation', required: true
      %br
      %h3 How did you hear about this club?
      = label :student, :info
      = text_field :student, 'info', required: true
      %br
      %br
      %br
      .form-actions
        = submit_tag 'Submit'
      %br
      %br
      %br
      %br

app/views/user_notifier/notify_user.text.erb
Hello <%= @user.name %>,

Your application status has been changed.

Best,
180 Degrees Consulting